accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView, articles_journals_of_user
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),
    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('<username>/profile/', view=articles_journals_of_user, name="user-profile"),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('about/',about,name="about"),
    path('contact/',contact,name="contact"),
    path('success/',success,name="success"),
]

journal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


static_root = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
media_root = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('journalApp.urls')),
    path('us/', include('home.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('user/', include("accounts.urls")),
] + static_root + media_root

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _


class CustomUser(AbstractUser):
    pass


class Activation(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)


class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, null=True, blank=False, verbose_name=_('User'), on_delete=models.CASCADE)
    about = models.TextField(max_length=2000, blank=True, null=True, verbose_name=_('About Me'))
    GENDER = ((None, _('Gender')), ('man', _('Man')), ('woman', _('Woman')))
    gender = models.CharField(choices=GENDER, blank=True, null=True, max_length=10, verbose_name=_('Gender'))
    profile_photo = models.ImageField(null=True, blank=True, verbose_name=_('Profile Photo'))
    birth_year = models.DateField(null=True, blank=True, verbose_name=_('Date of birth'))

    class Meta:
        verbose_name_plural = _('User Profiles')

    def get_screen_name(self):
        user = self.user
        if user.get_full_name():
            return user.get_full_name()
        return user.username

    def get_user_profile_url(self):
        url = reverse('accounts:user-profile', kwargs={'username': self.user.username})
        return url

    def user_full_name(self):
        if self.user.get_full_name():
            return self.user.get_full_name()
        return None

    def get_profile_photo(self):
        if self.profile_photo:
            return self.profile_photo.url
        return "/content/media/uploads/avatars/default.svg"

    def get_notification_count(self):
        from journalApp.models import Notification
        count = 0
        types = [1, 2, 3, 4, 5, 6]
        for i in Notification.objects.all():
            if i.notification_type in types:
                if (i.notification_type == 5 or i.notification_type == 6) and i.from_user == self.user and i.is_seen is False:
                    count += 1
                if (i.notification_type != 5 and i.notification_type != 6) and (i.to_user == self.user) and (i.is_seen is False):
                    count += 1
        if count > 0:
            return count

        return False

    def __str__(self):
        return "%s" % (self.get_screen_name())


def create_profile(sender, created, instance, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(create_profile, sender=CustomUser)

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings
from journalApp.models import Article_Journal, Journal

from .utils import (
    send_activation_email, send_reset_password_email, send_forgotten_username_email, send_activation_change_email,
)

from .forms import (
    SignInViaUsernameForm, SignInViaEmailForm, SignInViaEmailOrUsernameForm, SignUpForm,
    RestorePasswordForm, RestorePasswordViaEmailOrUsernameForm, RemindUsernameForm,
    ResendActivationCodeForm, ResendActivationCodeViaEmailForm, ChangeProfileForm, ChangeEmailForm,
)
from .models import Activation, CustomUser


class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = 'accounts/log_in.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME or settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

        if settings.LOGIN_VIA_EMAIL_OR_USERNAME:
            return SignInViaEmailOrUsernameForm

        return SignInViaUsernameForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request

        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME))
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)

        messages.success(request, _('Welcome again') + " " + request.user.first_name)

        return redirect(settings.LOGIN_REDIRECT_URL)


class SignUpView(GuestOnlyView, FormView):
    template_name = 'accounts/sign_up.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = False

        # Create a user record
        user.save()

        # Change the username to the "user_ID" form
        if settings.DISABLE_USERNAME:
            user.username = f'user_{user.id}'
            user.save()

        if settings.ENABLE_USER_ACTIVATION:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.save()

            send_activation_email(request, user.email, code)

            messages.success(
                request, _('We have received your registration, please click on the link sent for activation'))
        else:
            raw_password = form.cleaned_data['password1']

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            messages.success(request, _('Your Registration is Complete, Welcome to Us'))

        return redirect('index')


class ActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Activate profile
        user = act.user
        user.is_active = True
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('Your Account Has Been Activated Successfully!'))

        return redirect('accounts:log_in')


class ResendActivationCodeView(GuestOnlyView, FormView):
    template_name = 'accounts/resend_activation_code.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME:
            return ResendActivationCodeViaEmailForm

        return ResendActivationCodeForm

    def form_valid(self, form):
        user = form.user_cache

        activation = user.activation_set.first()
        activation.delete()

        code = get_random_string(20)

        act = Activation()
        act.code = code
        act.user = user
        act.save()

        send_activation_email(self.request, user.email, code)

        messages.success(self.request, _('New Activation Code Sent To Your E-Mail Address'))

        return redirect('accounts:resend_activation_code')


class RestorePasswordView(GuestOnlyView, FormView):
    template_name = 'accounts/restore_password.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME:
            return RestorePasswordViaEmailOrUsernameForm

        return RestorePasswordForm

    def form_valid(self, form):
        user = form.user_cache
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))

        if isinstance(uid, bytes):
            uid = uid.decode()

        send_reset_password_email(self.request, user.email, token, uid)

        return redirect('accounts:restore_password_done')


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/update_profile.html'
    form_class = ChangeProfileForm

    def get_initial(self):
        user = self.request.user

        initial = super().get_initial()

        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        initial['username'] = user.username
        initial['gender'] = user.userprofile.gender
        initial['profile_photo'] = user.userprofile.profile_photo
        initial['about'] = user.userprofile.about
        initial['birth_year'] = user.userprofile.birth_year

        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.username = form.cleaned_data['username']
        user.userprofile.gender = form.cleaned_data['gender']
        user.userprofile.profile_photo = form.cleaned_data['profile_photo']
        user.userprofile.about = form.cleaned_data['about']
        user.userprofile.birth_year = form.cleaned_data["birth_year"]
        user.save()
        user.userprofile.save()

        def msg():
            exp = []
            for i in form.fields:
                if form.initial[i] == form.cleaned_data.get(i, None) or form.cleaned_data.get(i, None):
                    exp.append("T")
                else:
                    exp.append("F")
            return exp

        if "F" in msg():
            messages.success(self.request, _('Your Profile Has Been Updated'))
        else:
            messages.success(self.request, _('Anything Changed :)'))

        return redirect('accounts:change_profile')


class ChangeEmailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_email.html'
    form_class = ChangeEmailForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        user = self.request.user
        email = form.cleaned_data['email']

        if settings.ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.email = email
            act.save()

            send_activation_change_email(self.request, email, code)

            messages.success(self.request, _('Please, Click On The Link We Sent For E-Mail Exchange'))
        else:
            user.email = email
            user.save()

            messages.success(self.request, _('Email Successfully Changed'))

        return redirect('accounts:change_email')


class ChangeEmailActivateView(View):

accounts/templates/accounts/log_in.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans 'Login Page' %}
{% endblock %}


{% block content %}


    <div class="content c-detail">
        <div class="block-detail" style="height: fit-content">

            <div class="post-profile">
                <div><i class="fas fa-sign-in-alt"></i> {% trans 'Login Form' %}</div>
            </div>

            <div class="post-content" style="height: fit-content;justify-content: center">
                {% if user.is_authenticated %}
                    <h3>Çoktan giriş yaptınız</h3>
                {% else %}
                    <form action="{% url "accounts:log_in" %}" method="post" style="width: fit-content;margin: 0 auto;text-align: center">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-lg btn-dark" style="letter-spacing: 2px">
                            {% trans "Sign In" %}
                        </button>
                        {% trans "or" %}
                        <a style="color:white" href="{% url 'accounts:sign_up' %}"
                           class="btn btn-dark btn-lg">
                            {% trans 'Sign Up' %}
                        </a>
                    </form>
                {% endif %}
            </div>

            <div class="post-content" style="height: fit-content;justify-content: center">
                <a href="{% url 'accounts:restore_password' %}">
                    <span class="btn btn-primary">
                        {% trans 'Forgot password?' %}
                    </span>
                </a>
            </div>
            <div class="post-content" style="height: fit-content;justify-content: center">

                <a href="{% url 'accounts:remind_username' %}">
                    <span class="btn btn-primary">
                        {% trans 'Forgot Your Username?' %}
                    </span>
                </a>
            </div>
            <div class="post-footer f-detail">

                <a href="{% url 'accounts:resend_activation_code' %}">
                    <span class="btn btn-primary">
                        {% trans 'Resend Activation Code' %}
                    </span>
                </a>
            </div>
        </div>
    </div>






{% endblock %}

accounts/templates/accounts/log_out.html
{% extends 'base.html' %}
{% load i18n %}


{% block title %}
    {% trans 'We hope you come again' %}
{% endblock %}

{% block content %}
    <div class="content c-detail">
        <div class="block-detail" style="height: fit-content">

            <div class="post-profile">
                <div><i class="fas fa-sign-out-alt"></i> {% trans 'Exit Page' %}</div>
            </div>

            <div class="post-content" style="height: fit-content;justify-content: center">
                <h4>{% trans 'Your Exit Has Been Made' %}</h4>

                {% trans 'We are waiting for you again to spend quality time' %}

                <a class="text-info" href="{% url 'accounts:log_in' %}">{% trans 'Sign in again' %}</a>

            </div>

        </div>
    </div>




{% endblock %}

accounts/templates/accounts/remind_username.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
    {% trans "Username Reminder" %}
{% endblock %}


{% block content %}
    <div class="profile-update">
        <div class="content c-detail">
            <div class="block-detail" style="   height: fit-content;">
                <div class="post-profile">


                    <h2> {% trans 'Username Reminder' %}</h2>


                </div>
                <div class="post-content" style="height: fit-content;border-bottom: none;">
                    {% crispy form %}
                </div>


            </div>
        </div>


    </div>

{% endblock %}

accounts/templates/accounts/resend_activation_code.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
    {% trans "Resend Activation Code" %}
{% endblock %}


{% block content %}
    <div class="profile-update">
        <div class="content c-detail">
            <div class="block-detail" style="   height: fit-content;">
                <div class="post-profile">


                    <h2> {% trans 'Resend Activation Code' %}</h2>


                </div>
                <div class="post-content" style="height: fit-content;border-bottom: none;">
                    {% crispy form %}
                </div>


            </div>
        </div>


    </div>

{% endblock %}

accounts/templates/accounts/restore_password.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
    {% trans "Password Reset" %}
{% endblock %}


{% block content %}
    <div class="profile-update">
        <div class="content c-detail">
            <div class="block-detail" style="   height: fit-content;">
                <div class="post-profile">


                    <h2> {% trans 'Password Reset' %}</h2>


                </div>
                <div class="post-content" style="height: fit-content;border-bottom: none;">
                    {% crispy form %}
                </div>


            </div>
        </div>


    </div>

{% endblock %}

accounts/templates/accounts/restore_password_confirm.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
    {% trans "Password Reset" %}
{% endblock %}


{% block content %}
    <div class="profile-update">
        <div class="content c-detail">
            <div class="block-detail" style="   height: fit-content;">
                <div class="post-profile">


                    <h2> {% trans 'Password Reset' %}</h2>


                </div>
                <div class="post-content" style="height: fit-content;border-bottom: none;text-align: center">
                    {% if validlink %}

                        <p>
                            {% trans 'Please Enter Your New Password Twice.' %}
                        </p>

                             {% crispy form %}

                    {% else %}

                        <div class="alert alert-danger">
                            {% trans 'This Link Is Invalid, Probably Used Before.' %}
                        </div>

                    {% endif %}

                </div>


            </div>
        </div>


    </div>

{% endblock %}

accounts/templates/accounts/restore_password_done.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
    {% trans "Password Reset" %}
{% endblock %}


{% block content %}
    <div class="profile-update">
        <div class="content c-detail">
            <div class="block-detail" style="   height: fit-content;">
                <div class="post-profile">


                    <h2> {% trans 'Password Reset' %}</h2>


                </div>
                <div class="post-content" style="height: fit-content;border-bottom: none;text-align: center">
                    <p>
                        {% trans "We have sent a series of instructions for renewal to your e-mail address you used while registering." %}

                    </p>
                    <p>
                        {% trans 'Please Check Your Mailbox.' %}

                    </p>

                    <p>
                        {% trans "If you have not received mail, please make sure that you enter the address that you entered while registering or check your spam folder." %}

                    </p>


                </div>


            </div>
        </div>


    </div>

{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans 'Sign up' %}
{% endblock %}

{% block style %}


{% endblock %}



{% block content %}


    <div class="content c-detail">
        <div class="block-detail" style="height: fit-content">

            <div class="post-profile">
                <div><i class="fa fa-user-plus"></i> {% trans 'Registration Form' %}</div>
            </div>

            <div class="post-content" style="height: fit-content;justify-content: center">
                {% if user.is_authenticated %}
                    <h3>Çoktan giriş yaptınız</h3>
                {% else %}
                    <form action="{% url "accounts:sign_up" %}" method="post"
                          style="width: fit-content;margin: 0 auto;text-align: center">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-lg btn-dark" style="letter-spacing: 2px">
                            {% trans "Sign Up" %}
                        </button>
                        {% trans "or" %}
                        <a style="color:white" href="{% url 'accounts:log_in' %}"
                           class="btn btn-lg btn-dark">
                            {% trans 'Sign In' %}
                        </a>
                    </form>
                {% endif %}
            </div>

        </div>
    </div>



{% endblock %}