accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView, articles_journals_of_user
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),
    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('<username>/profile/', view=articles_journals_of_user, name="user-profile"),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('about/',about,name="about"),
    path('contact/',contact,name="contact"),
    path('success/',success,name="success"),
]

journal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


static_root = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
media_root = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('journalApp.urls')),
    path('us/', include('home.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('user/', include("accounts.urls")),
] + static_root + media_root

journalApp/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt


journal_request = [
    path('onoff/<slug:slug>/', open_close_requesting, name="open_close"),
    path("request/<slug:slug>/", request_author_ship_view,name="authorship-request"),
    path("assessments/", JournalEditorAssessmentView.as_view(), name="editor-assessments"),
    path("reject/<int:id>/", JournalEditorAssessmentRejectView.as_view(), name="request-reject"),
    path("accept/<int:id>/", JournalEditorAssessmentAcceptView.as_view(), name="request-accept"),
    path("blocked/<int:id>/", JournalEditorAssessmentBlockView.as_view(), name="request-blocked"),
]


urlpatterns = [
    path('journals/', JournalView, name="journalindex"),
    path('journals_all/', JournalAll, name="journalall"),
    path('issue_create/', CreateIssueView.as_view(), name="issue_create"),
    path('journal_create/', CreateJournalView.as_view(), name="journal_create"),

    path('notification/<int:notification_id>/article/<slug:slug>/',ArticleNotification.as_view(), name="article_notification"),
    path('notification/<int:notification_id>/journal/<slug:slug>/',JournalNotification.as_view(), name="journal_notification"),
    path('notification/<int:notification_id>/request/',RequestNotification.as_view(), name="request_notification"),

    path('ajax/load-issues/', load_issues, name="load_issues"),

    path("fileUPload/",csrf_exempt(upload_file_view)),
    path("imageUPload/",csrf_exempt(upload_image_view)),
    path("fetchUrl/",csrf_exempt(fetch_url)),

    path('article_create/', CreateArticleView.as_view(), name="article_create"),
    path('journal_detail/<slug:slug>/', JournalDetailView, name="journal_detail"),
    path('', articles_journal_followed, name="index"),
    path('articledetail/<slug:slug>/', Article_Detail.as_view(), name="article_detail"),
    path('journaldetail/<slug:slug>/delete/', JournalDeleteView.as_view(), name="journal_delete"),
    path('articledetail/<slug:slug>/delete/', ArticleDeleteView.as_view(), name="article_delete"),
    path('journaldetail/<slug:slug>/update/', JournalUpdateView, name="journal_update"),
    path('articledetail/<slug:slug>/update/', ArticleUpdateView, name="article_update"),

    #ads.txt
    path('ads.txt/', ads, name="ads"),

    # category detail
    path('category/<slug:slug>/', Journal_CategoryDetail.as_view(), name="journal_category_detail"),

    # commentdelete
    path('comment/<int:pk>/delete/', Article_CommentDeleteView.as_view(), name="article_comment-delete"),

    # dergi_takip
    path('journal_follow/<slug:slug>/', add_or_remove_journal_follow, name="journal_follow"),
    path('journal_follow_users/<slug:slug>/', journal_follow_user, name="journal_follow_user"),

    # article_like
    path('favorite-page/<slug:slug>/', add_or_remove_favorite_article, name="favorite-article-page"),
    path('favorite-page-users/<slug:slug>/', article_list_favorite_article_user, name="favorite-article-user"),

]

urlpatterns += journal_request

journalApp/models.py
from django.db import models
from django.contrib.auth.models import Group
from uuid import uuid4
import os, datetime
from django.template.defaultfilters import slugify
from django_editorjs import EditorJsField
from hitcount.models import HitCount
from unidecode import unidecode
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from accounts.models import CustomUser

AUTHORSHIP_STATUS = (
    ('requested', _('Request')),
    ('accepted', _('Accept')),
    ('rejected', _('Reject')),
    ('banned', _('Request Exceeded')),
    ('blocked', _('Blocked')),
    ('created', _('Created'))
)

REQUESTING_STATUS = (
    ('open', _('Open')),
    ('closed', _('Close')),
)

JOURNAL_MEMBER_STATUS = (
    ('founder', _('Founder')),
    ('admin', _('Admin')),
    ('author', _('Author')),
    ('any', _('Any')),
)


def upload_to(instance, filename):
    extension = filename.split(".")[-1]
    new_name = "%s.%s" % (str(uuid4()), extension)
    unique_id = instance.unique_id
    return os.path.join("uploads", unique_id, new_name)


class Journal_Category(models.Model):
    title = models.CharField(
        max_length=150,
        verbose_name=_("Journal Category"))

    slug = models.SlugField(
        unique=True,
        editable=False)

    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Journal_Category, self).save(*args, **kwargs)


class Journal(models.Model):
    class Meta:
        verbose_name = _("Journal")
        verbose_name_plural = _("Journals")
        ordering = ["-created"]

    journal_editor = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="journal_editor",
        default=1)

    journal_image = models.ImageField(
        upload_to=upload_to,
        null=True,
        blank=True,
        default="uploads/onecki.jpg",
        verbose_name=_("Cover photo"))

    unique_id = models.CharField(
        max_length=100,
        editable=False,
        null=True)

    journal_name = models.CharField(
        max_length=250,
        verbose_name=_("Journal Name"),
        blank=False,
        null=True)

    slug = models.SlugField(
        null=True,
        unique=True,
        editable=False)

    requesting_status = models.CharField(
        max_length=50,
        choices=REQUESTING_STATUS,
        default="closed")

    created = models.DateTimeField(
        auto_now_add=True)

    updated = models.DateTimeField(
        auto_now=True)

    category = models.ForeignKey(
        Journal_Category,
        on_delete=models.CASCADE,
        related_name="category_of_journal",
        verbose_name=_("Journal Category"))

    def __str__(self):
        return self.journal_name

    def get_journal_follow_count(self):
        return self.journalfollow.count()

    def get_added_follower_user_id(self):
        return self.journalfollow.values_list(
            'journal__id',
            flat=True)

    def get_added_follower_user(self):
        return self.journalfollow.values_list(
            'user__username',
            flat=True)

    def get_added_follower_user_as_object(self):
        data_list = []
        for i in self.journalfollow.all():
            data_list.append(i.user)
        return data_list

    def get_requesting_status(self):
        return self.requesting_status

    def get_unique_slug(self):
        counter = 0
        slug = slugify(unidecode(self.journal_name))
        new_slug = slug
        while Journal.objects.filter(slug=new_slug).exists():
            counter += 1
            new_slug = "%s-%s" % (slug, counter)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            new_unique_id = str(uuid4())
            self.unique_id = new_unique_id
            self.slug = self.get_unique_slug()

        else:
            journal = Journal.objects.get(slug=self.slug)
            if journal.journal_name != self.journal_name:
                self.slug = self.get_unique_slug()

        super(Journal, self).save(*args, **kwargs)


class RequestAuthorShip(models.Model):
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE)
    journal = models.ForeignKey(
        Journal,
        on_delete=models.CASCADE)
    status = models.CharField(
        max_length=50,
        choices=AUTHORSHIP_STATUS,
        default="requested")
    member_status = models.CharField(
        max_length=50,
        choices=JOURNAL_MEMBER_STATUS,
        default="author")

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.journal.journal_name


YEAR_CHOICES = []
for r in range(1950, (datetime.datetime.now().year + 1)):
    YEAR_CHOICES.append((r, r))


class Journal_Issue(models.Model):
    journal = models.ForeignKey(
        Journal,
        null=False,
        blank=False,
        verbose_name=_('Journal'),
        on_delete=models.CASCADE)

    name = models.CharField(
        max_length=150,
        verbose_name=_("Issue Name"))

    year = models.IntegerField(
        _('Year'),
        choices=YEAR_CHOICES,
        default=datetime.datetime.now().year)

    created = models.DateTimeField(
        auto_now_add=True)

    slug = models.SlugField(
        unique=True,
        editable=False)

    def __str__(self):
        return str(self.year) + " / " + self.name

    def get_unique_slug(self):
        sayi = 0
        slug = slugify(unidecode(self.name))
        new_slug = slug
        j_issue = Journal_Issue.objects.filter(slug=new_slug)
        while j_issue.exists():
            sayi += 1
            new_slug = "%s-%s" % (slug, sayi)

        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            new_unique_id = str(uuid4())
            self.unique_id = new_unique_id
            self.slug = self.get_unique_slug()
        else:
            issue = Journal_Issue.objects.get(slug=self.slug)
            if issue.name != self.name:
                self.slug = self.get_unique_slug()
        print(self.slug)
        super(Journal_Issue, self).save(*args, **kwargs)


class Article_Journal(models.Model):
    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
        ordering = ["-created"]

    author_of_article = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="author_of_article")

    journal_name_of_article = models.ForeignKey(
        Journal,
        on_delete=models.CASCADE,
        verbose_name=_("Select the Journal"),
        related_name="journal_name_of_article")

    issue_name_of_article = models.ForeignKey(
        Journal_Issue,
        on_delete=models.CASCADE,
        verbose_name=_("Select the Issue"),
        related_name="issue_name_of_article")

    article_image = models.ImageField(
        upload_to=upload_to,
        null=True,
        blank=True,
        default="uploads/onecki.jpg",
        verbose_name=_("Image"))

    unique_id = models.CharField(
        max_length=100,
        editable=False,
        null=True)

    article_title = models.CharField(
        max_length=250,
        verbose_name=_("Title"),
        blank=False,
        null=True)

    hit_count_generic = GenericRelation(
        HitCount,
        object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')

    article_content = EditorJsField(
        null=True,
        blank=False,
        verbose_name=_("Content"),
        editorjs_config={
            "tools": {
                "Image": {
                    "config": {
                        "endpoints": {
                            "byFile": "/imageUPload/",
                            "byUrl": "/imageUPload/",
                        },
                        "additionalRequestsHeaders": [
                            {"Content-Type": "multipart/form-data"}
                        ]
                    }
                },
                "Attaches": {
                    "config": {
                        "endpoint": "/fileUPload/"
                    }
                },
                "Link": {
                    "config": {
                        "endpoint": "/fetchUrl/"
                    },
                }
            }
        })

    slug = models.SlugField(
        null=True,
        unique=True,
        editable=False)

    created = models.DateTimeField(
        auto_now_add=True)

    updated = models.DateTimeField(
        auto_now=True)

    def __str__(self):
        return "%s" % (self.article_title)

    def get_comments_article(self):
        return self.comments_article.all().count()

    def get_article_comments(self):
        return self.comments_article.all()

    def get_added_favorite_article_user(self):
        fav_list = self.favorite_article_journal
        return fav_list.values_list('user__username', flat=True)

    def get_added_favorite_article_user_as_object(self):
        data_list = []
        for i in self.favorite_article_journal.all():
            data_list.append(i.user)
        return data_list

    def get_favorite_article_count(self):
        return self.favorite_article_journal.count()

    def get_unique_slug(self):
        sayi = 0
        slug = slugify(unidecode(self.article_title))
        new_slug = slug
        while Article_Journal.objects.filter(slug=new_slug).exists():
            sayi += 1
            new_slug = "%s-%s" % (slug, sayi)

        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            new_unique_id = str(uuid4())
            self.unique_id = new_unique_id
            self.slug = self.get_unique_slug()
        else:

journalApp/templates/journalApp/articledel.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Makale Silme
{% endblock %}


{% block style %}

{% endblock %}

{% block content %}


    <form action="" method="post" class="mb-20">
        {% csrf_token %}
        <p class="alert alert-danger text-center">Bu Makaleyi Silmek İstediğinize Emin misiniz ?</p>
        <div style="text-align: center">
            <button type="submit" class="btn btn-primary radius">SİL</button>
            <a href="{% url 'article_detail' object.slug %}" class="btn btn-danger radius">İPTAL</a>
        </div>
    </form>


{% endblock %}

journalApp/templates/journalApp/create_article.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans "Create an Article" %}
{% endblock %}

    
{% block css %}

    <style type="text/css">
        .hidden {
            display: none;
        }

        #articleForm {
            width: 100%;
        }

        [data-editorjs-wrapper] {
            max-width: 100% !important;
            width: 100%;
            border-radius: 4px;
            background: #000 !important;
            /* color: #000; */
            padding: 1.2em;
            display: inline-block;
            border: 1px solid #ccc;
            color: white !important;
        }

        div[data-editorjs-holder] {
            max-width: 100% !important;
        }

        @media (max-width: 767px) {
            div[data-editorjs-holder] {
                width: 100% !important;
            }
        }
         #div_id_article_content div{
            text-align: left;
        }

         .ce-paragraph--justify {
            text-align: justify !important;
         }
         .ce-paragraph--center {
            text-align: center !important;
         }
         .ce-paragraph--left {
            text-align: left !important;
         }
         .ce-paragraph--right {
            text-align: right !important;
         }

        .ce-block__content {
            max-width: calc(100% - 40px);
        }

        .ce-toolbar__content{
            max-width: calc(100% - 40px);
        }

        .cdx-notifies {
            z-index: 52 !important;
        }

        .cdx-warning__title {
            background-color: #fff3cd;
            color:black;;
        }
         .ce-delimiter {
            line-height: 1.6em;
            width: 100%;
            text-align: center !important;
        }

    </style>

{% endblock %}



{% block content %}
    <div class="container">
        <div class="content">
            {% crispy form %}
        </div>
    </div>
{% endblock %}

{% block alt_icerik %}
    <script>
    $("#id_journal_name_of_article").change(function () {
        const url = $("#articleForm").attr("data-issues-url");
        console.log(url)
        const journalId = $(this).val();
        $.ajax({                      
            url: url,                 
            data: {
                'journal_id': journalId     
            },
            success: function (data) {   

                let html_data = '<option value="">---------</option>';
                data.forEach(function (issue) {
                    html_data += `<option value="${issue.id}">${issue.year} / ${issue.name}</option>`
                });
                $("#id_issue_name_of_article").html(html_data);

            }
        });

    });
</script>

{% endblock %}

journalApp/templates/journalApp/create_dergi.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans "Create a Journal" %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="content">
            {% crispy form %}
        </div>
    </div>
{% endblock %}

journalApp/templates/journalApp/create_issue.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans "Create an Issue" %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="content">
            {% crispy form %}
        </div>
    </div>
{% endblock %}

journalApp/templates/journalApp/dergidel.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Dergi Silme
{% endblock %}


{% block style %}

{% endblock %}

{% block content %}


    <form action="" method="post" class="mb-20">
        {% csrf_token %}
        <p class="alert alert-danger">Bu Dergiyi Silmek İstediğinize Emin misiniz ?</p>
        <div style="text-align: center">
            <button type="submit" class="btn btn-primary radius">SİL</button>
            <a href="{% url 'journal_detail' object.slug %}" class="btn btn-danger radius">İPTAL</a>
        </div>
    </form>
      


{% endblock %}

journalApp/templates/journalApp/journal_editor_assessments.html
{% extends "base.html" %}

{% block content %}

    <table>
        <thead>
        <tr>
            <th>kullanıcı</th>
            <th>dergi</th>
            <th>işlemler</th>
        </tr>
        </thead>
        <tbody>
        {% if assessments %}
            {% for assest in assessments %}
                <tr>
                    <td>{{ assest.user.username }}</td>
                    <td>{{ assest.journal }}</td>
                    <td>
                        <a class="btn btn-success" href="/accept/{{ assest.id }}">kabul et</a>
                        <a class="btn btn-danger" href="/reject/{{ assest.id }}">reddet</a>
                        <a class="btn btn-danger" href="/blocked/{{ assest.id }}">engelle</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            hiç başvuru yok
        {% endif %}
        </tbody>
    </table>
{% endblock %}

journalApp/templates/journalApp/show_notifications.html
{% load i18n %}
{% load static %}

<a href="#" role="button" id="dropdownMenuLink2" style="color:black" data-toggle="dropdown" aria-haspopup="true"
   aria-expanded="false">
    <img src="{% static 'icons/notification-frame.svg' %}" alt="">
    <div class="noti-num">
    	<span class="text-xs">
          	{% if count > 0 %} {{ count }} {% else %} 0 {% endif %}            
        </span>
    </div>
</a>

<div class="dropdown-menu" aria-labelledby="dropdownMenuLink2">

    {% if count == 0 %}

        <a class="dropdown-item" href="#">
            {% trans "No Notification" %}
        </a>

    {% else %}

        {% for notification in notifications %}

            {% if notification.article %}

                {% if notification.notification_type == 1 %}

                    <a class="dropdown-item"
                       href="{% url "article_notification" notification.id notification.article.slug %}">
                        @{{ notification.from_user }} liked your article
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" style="font-size: 2rem">&times;</span>
                        </button>
                    </a>


                {% endif %}

                {% if notification.notification_type == 2 %}

                    <a class="dropdown-item"
                       href="{% url "article_notification" notification.id notification.article.slug %}">
                        @{{ notification.from_user }} commented on your article
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" style="font-size: 2rem">&times;</span>
                        </button>
                    </a>

                {% endif %}


            {% elif notification.comment %}

                {% if notification.notification_type == 1 %}

                    <a class="dropdown-item"
                       href="{% url "article_notification" notification.id notification.comment.article.slug %}">
                        @{{ notification.from_user }} liked your comment
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" style="font-size: 2rem">&times;</span>
                        </button>
                    </a>

                {% endif %}

                {% if notification.notification_type == 2 %}

                    <a class="dropdown-item"
                       href="{% url "article_notification" notification.id notification.comment.article.slug %}">
                        @{{ notification.from_user }} replied to your comment
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" style="font-size: 2rem">&times;</span>
                        </button>
                    </a>

                {% endif %}

            {% elif notification.journal %}

                {% if notification.notification_type == 3 %}

                    <a class="dropdown-item" href="{% url "request_notification" notification.id %}">
                        @{{ notification.from_user }} requested for Authorship
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" style="font-size: 2rem">&times;</span>
                        </button>
                    </a>

                {% endif %}

                {% if notification.notification_type == 4 %}

                    <a class="dropdown-item"
                       href="{% url "journal_notification" notification.id notification.journal.slug %}">
                        @{{ notification.from_user }} subscribed {{ notification.journal.journal_name }}
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" style="font-size: 2rem">&times;</span>
                        </button>
                    </a>

                {% endif %}

                {% if notification.notification_type == 5 %}

                    <a class="dropdown-item"
                       href="{% url "request_notification" notification.id %}">
                        @{{ notification.to_user }} has accepted your reqeuest
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" style="font-size: 2rem">&times;</span>
                        </button>
                    </a>

                {% endif %}

                {% if notification.notification_type == 6 %}

                    <a class="dropdown-item"
                       href="{% url "request_notification" notification.id %}">
                        @{{ notification.to_user }} has rejected your request
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true" style="font-size: 2rem">&times;</span>
                        </button>
                    </a>

                {% endif %}

            {% endif %}

        {% endfor %}


    {% endif %}

</div>
	

journalApp/templates/journalApp/update_article.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans "Update Article" %}
{% endblock %}

     
{% block css %}

    <style type="text/css">
        .hidden {
            display: none;
        }

        #articleForm {
            width: 100%;
        }

        [data-editorjs-wrapper] {
            max-width: 100% !important;
        }

        div[data-editorjs-holder] {
            max-width: 100% !important;
        }
  
        @media (max-width: 767px) {
            div[data-editorjs-holder] {
                width: 100% !important;
            }
        }
         #div_id_article_content div{
            text-align: left;
        }

         .ce-paragraph--justify {
            text-align: justify !important;
         }
         .ce-paragraph--center {
            text-align: center !important;
         }
         .ce-paragraph--left {
            text-align: left !important;
         }
         .ce-paragraph--right {
            text-align: right !important;
         }

        .ce-delimiter {
            line-height: 1.6em;
            width: 100%;
            text-align: center !important;
        }
        .ce-block__content {
            max-width: calc(100% - 40px);
        }

        .ce-toolbar__content{
            max-width: calc(100% - 40px);
        }

        .cdx-notifies {
            z-index: 52 !important;
        }
        
        .cdx-warning__title {
            background-color: #fff3cd;
        }

    </style>

{% endblock %}



{% block content %}
    <div class="container">
        <div class="content">
            {% crispy form %}
        </div>
    </div>
{% endblock %}

{% block alt_icerik %}
    <script>
    $("#id_journal_name_of_article").change(function () {
        const url = $("#articleForm").attr("data-issues-url");  // get the url of the `load_cities` view
        const journalId = $(this).val();  // get the selected country ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'journal_id': journalId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                console.log(data);
                let html_data = '<option value="">---------</option>';
                data.forEach(function (issue) {
                    html_data += `<option value="${issue.id}">${issue.year} / ${issue.name}</option>`
                });
                $("#id_issue_name_of_article").html(html_data);

            }
        });

    });
</script>

{% endblock %}

journalApp/templates/journalApp/update_dergi.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Dergi Güncelleme
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
    <h4 style="margin:0 auto">Dergini Güncelle</h4>
    {% crispy form %}
{% endblock %}